export default {
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    PERSIST_LOGIN: 'PERSIST_LOGIN',
    CREATE_REQUEST: 'CREATE_REQUEST',
    NEW_REQUEST: 'NEW_REQUEST',
    GET_REQUESTS: 'GET_REQUESTS',
    GET_REQUEST:'GET_REQUEST',
  };
  