export default {
    LOGIN: 'LOGIN',
    SIGN_UP: 'SIGN_UP',
    LOGOUT: 'LOGOUT',
    PERSIST_LOGIN: 'PERSIST_LOGIN',
    CREATE_REQUEST: 'CREATE_REQUEST',
    NEW_REQUEST: 'NEW_REQUEST',
    GET_REQUESTS: 'GET_REQUESTS',
    GET_REQUEST:'GET_REQUEST',
    UPDATE_REQUEST:'UPDATE_REQUEST',
    GET_ADMIN_REQUESTS:'GET_ADMIN_REQUESTS',
    FILTER_REQUESTS:'FILTER_REQUESTS',
    APPROVE_REQUEST:'APPROVE_REQUEST',
    DISAPPROVE_REQUEST:'DISAPPROVE_REQUEST',
    RESOLVE_REQUEST:'RESOLVE_REQUEST',
  };
  